name: core_data
description: Contains repositories that are built on top of network and local data sources.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_network:
    path: ./../core_network
  core_datastore:
    path: ./../core_datastore
  core_database:
    path: ./../core_database
  get_it: 7.2.0
  injectable: 1.5.3
  cupertino_icons: ^1.0.2
  logger: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: 1.5.4
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
