name: lib_use_case
description: Contains use cases that serve feature modules.
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_data:
    path: ./../core_data
  core_model:
    path: ./../core_model
  get_it: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
